### ISSUE TITLE
Research Order Handling 3rd Party Softwares or APIs

### ISSUE THREAD

**Issue by rcmendez23** [boston-microgreens/grow-app-project#144]

**Comment by rcmendez23** [comment]
[https://www.tradegecko.com/product-tour/sales/order-fulfillment-software](url)
[https://www.primaseller.com/features/b2b-order-management-software](url)
[https://www.orderhive.com/multi-channel-listing-software.html](url)

**Comment by willstenzel** [comment]
I looked into a few options and it looks like the software that is already out there would be tough to integrate into our own system to be able to keep track of all the orders. One possibility is to build the e-commerce site on top the grow-app application, using a [free e-commerce template](https://mdbootstrap.com/freebies/jquery/e-commerce/) to speed up the development.
