### ISSUE TITLE
Bring back testing!

### ISSUE THREAD

**Issue by rcmendez23** [boston-microgreens/grow-app-project#155]
- Go through selenium tests and fix broken ones
- Add new tests for basic inventory functions

**Comment by Sri-V** [comment]
is this open ?

**Comment by rcmendez23** [comment]
@Sri-V Yes!

**Comment by Sri-V** [comment]
@rcmendez23 Am facing issues with setting this project in my local. am facing below error now :
'''    raise KeyError(key) from None
KeyError: 'DJANGO_SECRET_KEY'  '''
Can you help with this ?

**Comment by rcmendez23** [comment]
@Sri-V Try again? we added the local secret key in #239
