### ISSUE TITLE
Customer login & account creation

### ISSUE THREAD

**Issue by rcmendez23** [boston-microgreens/grow-app-project#156]
- Allow customers to register an account with orders app
- Allow customers to securely log in with their credentials
- 3 Tiers of Access: No login required, Customer or Admin Login Required, Admin Login Required

**Comment by rcmendez23** [comment]
How do we make certain parts of the orders app only accessible by admins?

**Comment by erinburba** [comment]
It looks like the @login_required decorator we use on some of the views has options that we may be able to use to distinguish signed-in customers from admins.

**Comment by willstenzel** [comment]
> How do we make certain parts of the orders app only accessible by admins?
There also a decorator for limiting access to staff members 

```from django.contrib.admin.views.decorators import staff_member_required
@staff_member_required```

**Comment by willstenzel** [comment]
Also what do you guys think about using something like django-allauth to allow customers to do social login so they don't have to go through the trouble of making a new account

**Comment by erinburba** [comment]
That's a good idea - maybe restrict to just Google as a provider unless any of the others are prominent among the customer base.

**Comment by rcmendez23** [comment]
Thanks, guys. Yes I was looking into the login stuff on Friday. I think social login is an interesting idea, but as they are professional restaurants, I don't know if it will even be more convenient to login via google or social accounts since they won't be personal accounts. Definitely google makes the most sense if we are going to do this.

**Comment by rcmendez23** [comment]
https://docs.djangoproject.com/en/2.2/topics/auth/default/
