### ISSUE TITLE
Storing Product Images

### ISSUE THREAD

**Issue by rcmendez23** [boston-microgreens/grow-app-project#175]
How do we keep track of product images, relate them with products in the database and display them on the site? 

One idea: Product model has a field that holds file name(s) of an image.
Another idea: Strict naming conventions of images

**Comment by willstenzel** [comment]
I think that creating an `ImageField` in on the product is probably the best option. It will make it very easy to upload and display the images

**Comment by rcmendez23** [comment]
- Create ImageField in Product
- Load images into shop and product_details pages

**Comment by rcmendez23** [comment]
#217
